### ISSUE TITLE
Integration with use-ruby

### ISSUE THREAD

**Issue by eregon** [MSP-Greg/actions-ruby#1]
Hello, and thank you for this action!

I am the author of https://github.com/eregon/use-ruby-action and would like to see what it would take to make it work on Windows too.

The idea of that action is to reuse prebuilt binaries, so setting up Ruby is just download + add to PATH.
For Linux and macOS I use this repo which automatically compiles Ruby:
https://github.com/eregon/ruby-install-builder/

For fun I tried to run it on Windows with `shell: bash` (which uses the Git shell, so quite limited) but that failed early: https://github.com/eregon/ruby-install-builder/commit/ca7c2421117780dac91d309189e08dd41c8ef0ec/checks?check_suite_id=380675014

Looking at https://github.com/MSP-Greg/actions-ruby/blob/master/lib/main.js I wonder which parts are needed. It looks quite complicated.
Of course, it would be most convenient if we can use the RubyInstaller2 binaries.

OTOH, do we need to install extra packages and update MSYS2?
That seems to take a while (1min16s in [example](https://github.com/ruby/spec/runs/371220841)), so I'd like to avoid it if possible.

**Comment by eregon** [comment]
cc @larskanis you might be interested in this.

**Comment by MSP-Greg** [comment]
@eregon

I need to take a good look at what you've done.  I looked earlier, but just a quick glance...

I set this up to work with Ruby 2.3 (RubyInstaller), the latest releases of Ruby 2.4 thru 2.6 (RubyInstaller2), and ruby-loco.

I do a bit of work with extension gems, in particular, CI on Windows, so I set this up mostly for that purpose.  But, normal (Ruby only) gems don't need that.

One question I've wondered about is what versions of Ruby should be supported, both major/minor and within major/minor.  RubyInstaller2 (@larskanis) has all the versions from 2.4 forward.

If this work goes public, I'm sure someone will want to test against 2.6.3, or 2.5.5, etc.  That wasn't available on AppVeyor, but I believe it is on Travis (?)

**Comment by eregon** [comment]
On https://rubyinstaller.org/downloads/ I see there are packaged versions together with the DevKit.
This is probably the simplest since then it's more likely to just work.

However I only see `.exe` for that on the website and https://github.com/oneclick/rubyinstaller2/releases.
Is there a way to run the `.exe` installer from the command line (i.e., in GitHub Actions)?

**Comment by MSP-Greg** [comment]
You can download the 7x files, there are three MSYS2 installs on Actions, one in each Windows Ruby.  I symlink to one in the code here...

**Comment by eregon** [comment]
Thanks, I found https://github.com/MSP-Greg/actions-ruby/blob/50b691db4e69c5499f37e0927e97a47e67094422/action.yml#L14-L16
But I guess that will break when GitHub updates Ruby 2.6 to 2.6.5 in the toolcache.
We could probably take the last entry of `C:\hostedtoolcache\windows\Ruby` though.

It might be better to not rely on the toolcache if possible, as it often changes.

Maybe we can run the installer in very silent mode, including `ridkinstall` and repackage the whole as a single or two archives:
https://github.com/oneclick/rubyinstaller2/wiki/FAQ#q-how-do-i-perform-a-silentunattended-install-with-the-rubyinstaller
Or if that's fast enough just run it directly in `use-ruby`.

**Comment by MSP-Greg** [comment]
Re Windows, there have been users (other than Ruby users) who have asked for an MSYS2 install, I also asked for one.

I don't really know the best place to ask, and also whether they'll confirm anything.

> It might be better to not rely on the toolcache if possible, as it often changes.

Actually, I don't believe it has been updated since the beta started.  That's part of the reason all of this has happened.

**Comment by eregon** [comment]
https://github.com/actions/virtual-environments/issues/30 seems the best issue I found so far regarding adding MSYS2 in the base image.

**Comment by MSP-Greg** [comment]
Almost 4 months ago:
https://github.community/t5/GitHub-Actions/Windows-MSYS2-Ruby/m-p/30885

**Comment by larskanis** [comment]
I didn't work with Github Actions so far. But install of the RubyInstaller exe files is [pretty easy](https://github.com/sparklemotion/nokogiri/commit/cc80904c9770e83df97548e02f5c829fe24a25bc). There is also a daily build of RubyInstaller-head available with ruby-master and up-to-date MSYS2: https://github.com/oneclick/rubyinstaller2/releases/tag/rubyinstaller-head
The only thing to note is that the installer must be started per cmd. Otherwise it's running in the background and processing doesn't wait.

**Comment by eregon** [comment]
I tried a few approaches in https://github.com/eregon/ruby-install-builder/actions on branch `windows2`.
Downloading the installer and running it with `cmd /c ruby-setup.exe /verysilent /dir=C:/Ruby26` seems to work well.
It takes about 17 seconds to install in GitHub Actions.
With the DevKit, that becomes 2 minutes to install (too long for CI I think).

I tried repackaging the installed Ruby+DevKit, and that gives a 300MB .tar.gz, which is kind of large.
Not sure how fast it would be to download and extract that on Windows.

The PATH in GitHub Actions seems quite messy and `gem install json` ends up working even without a DevKit with the original PATH (it finds some mingw installation). Filtering as done in this action seems a good idea. By default Ruby 2.5.5 is on PATH,which is kind of inconsistent with other OS where there is no `ruby` by default.

I think in the end I'll use an approach very similar to this action. @MSP-Greg is certainly more experienced than I am with Windows.

**Comment by MSP-Greg** [comment]
@eregon 

First of all, thank you for your work on this.

I've been using MSYS2 for a few years, also for building packages.  I tried various ways to install it, and especially for a 'pure ruby' gem/repo, the time was just too long.

From my perspective, I've seen many issues raised since the Actions beta started, and with few exceptions, very few **actions** were taken to fix the issues.

When the CI doesn't even work with `[ci skip]` / `[skip ci]`, I gotta wonder...

So, I'm waiting to see what happens.  If they start making changes and moving things into GH repos, all the better.  Otherwise, we need to think about how best to do it ourselves.

The main thing I'm wondering about is support for versions other than 'last teeny', and whether we need to support master 'pre' builds.  Given that the logic for that sort of thing is messy, it would be best to support from the start (?)

**Comment by eregon** [comment]
FWIW I tried repackaging installed Ruby+DevKit as a .7z, that's 150MB (instead of 300MB .tar.gz, nice).
However it takes 1min25s to decompress, that's rather depressing:
https://github.com/eregon/ruby-install-builder/runs/374538859
I suppose that's mostly due to very slow disk IO on Windows?

So I guess the only fast way for now is to rely on the existing MSYS2 install in `C:\hostedtoolcache\windows\Ruby\2.6.3\x64\msys6`.

**Comment by MSP-Greg** [comment]
Yeah, been there, done that.  I'm hoping they add an MSYS2 install independent of the Ruby installs.

Everywhere I've seen discussion, they're very vague about any disk image updates.

JFYI, I added Ruby 2.7.0 here.

**Comment by larskanis** [comment]
@eregon You're right, switching to a different compression algorithm doesn't have a big impact on install speed. Windows is awfully slow at handling small files. RubyInstaller uses [lzma2 compression](https://github.com/oneclick/rubyinstaller2/blob/1435e9db8e97743dfd924280b2118ce8cdb9b064/recipes/installer-inno/rubyinstaller.iss.erb#L42).

Possibly my idea is ridiculous, because I didn't try Github Actions so far. But if I understood it right, it has RubyInstaller-Devkit 2.4, 2.5 and 2.6 preinstalled with full Devkit? So isn't it an option to just 
```
mv c:/ruby26-x64/msys64 c:/
```
and install RubyInstaller-head without Devkit (or Ruby-Loco)? The `msys64` folder is usually a totally standard MSYS2 setup with no specifics to any particular Ruby or RubyInstaller version. The only difference is that some pacman packages (gcc, autotools, etc) are preinstalled. If it's in `c:/msys64` each RubyInstaller version will find and use it.

**Comment by MSP-Greg** [comment]
@larskanis

You're idea is good, as it's what I'm doing in this repo.  I'm just making a `C:\msys64` symlink to the 2.6.3 DevKit, and then downloading your RI2 7z files.  Ok, I'm using ruby-loco for master...

It also allows 2.3.3.  Some extension gems will compile and test with MSYS2 built *.so files...

**Comment by eregon** [comment]
> JFYI, I added Ruby 2.7.0 here.

Thanks! And thank you @larskanis for building it!

I got Ruby 2.4-2.7 working now in `use-ruby-action` with https://github.com/eregon/use-ruby-action/commit/101f62de1d2aff7846f52bf23989d934bd75874d.

It has similar logic as this action but simplified:
https://github.com/eregon/use-ruby-action/blob/101f62de1d2aff7846f52bf23989d934bd75874d/windows.js

And indeed it just reuses the MSYS2 from the hostedtoolcache, which means the whole action takes just 5 seconds to run: https://github.com/eregon/use-ruby-action/runs/374628258

Drawbacks are probably a slightly older MSYS2 than when using `base: update` in this action (but that takes 1 minute).

And currently bundler is not installed in those `.7z` archives, while it is for Ubuntu/macOS with https://github.com/eregon/ruby-install-builder/, I should fix that.

**Comment by MSP-Greg** [comment]
> And currently bundler is not installed in those .7z archives

Should be for Ruby 2.6 and later.

Not right now, but I'll have a look re adding the base, mingw & msys2 parameters.  They are helpful, as a lot of devs aren't familiar with MSYS2.  Obviously, they'd be ignored for other OS's...

Thanks, Greg

**Comment by eregon** [comment]
> Should be for Ruby 2.6 and later.

Right, of course. But for Ruby <= 2.5 it's not there but I'd guess almost all Ruby CI jobs want it.
